# Generated by Django 4.2.11 on 2025-04-13 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='products.productmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='propertydecimal',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='propertyinteger',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='propertymultipledecimals',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='propertymultipleintegers',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='propertymultiplestrings',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='propertyrangedecimal',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='propertyrangeinteger',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='propertystring',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='subcategoryproperty',
            name='ranged',
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='subcategoryproperty',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('MULTIPLE_STRINGS', 'Multiple Strings'), ('MULTIPLE_INTEGERS', 'Multiple Integers'), ('MULTIPLE_DECIMALS', 'Multiple Decimals'), ('RANGED_INTEGER', 'Ranged Integer'), ('RANGED_DECIMAL', 'Ranged Decimal')], max_length=20),
        ),
        migrations.CreateModel(
            name='DecimalProperty',
            fields=[
                ('baseproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproperty')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('products.baseproperty',),
        ),
        migrations.CreateModel(
            name='IntegerProperty',
            fields=[
                ('baseproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproperty')),
                ('value', models.IntegerField()),
            ],
            bases=('products.baseproperty',),
        ),
        migrations.CreateModel(
            name='MultipleDecimalsProperty',
            fields=[
                ('baseproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproperty')),
                ('values', models.JSONField()),
            ],
            bases=('products.baseproperty',),
        ),
        migrations.CreateModel(
            name='MultipleIntegersProperty',
            fields=[
                ('baseproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproperty')),
                ('values', models.JSONField()),
            ],
            bases=('products.baseproperty',),
        ),
        migrations.CreateModel(
            name='MultipleStringsProperty',
            fields=[
                ('baseproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproperty')),
                ('values', models.JSONField()),
            ],
            bases=('products.baseproperty',),
        ),
        migrations.CreateModel(
            name='RangedDecimalProperty',
            fields=[
                ('baseproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproperty')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('products.baseproperty',),
        ),
        migrations.CreateModel(
            name='RangedIntegerProperty',
            fields=[
                ('baseproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproperty')),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
            ],
            bases=('products.baseproperty',),
        ),
        migrations.CreateModel(
            name='StringProperty',
            fields=[
                ('baseproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.baseproperty')),
                ('value', models.CharField(max_length=255)),
            ],
            bases=('products.baseproperty',),
        ),
        migrations.DeleteModel(
            name='ModelProperty',
        ),
        migrations.DeleteModel(
            name='PropertyDecimal',
        ),
        migrations.DeleteModel(
            name='PropertyInteger',
        ),
        migrations.DeleteModel(
            name='PropertyMultipleDecimals',
        ),
        migrations.DeleteModel(
            name='PropertyMultipleIntegers',
        ),
        migrations.DeleteModel(
            name='PropertyMultipleStrings',
        ),
        migrations.DeleteModel(
            name='PropertyRangeDecimal',
        ),
        migrations.DeleteModel(
            name='PropertyRangeInteger',
        ),
        migrations.DeleteModel(
            name='PropertyString',
        ),
        migrations.AddField(
            model_name='baseproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategoryproperty'),
        ),
        migrations.AlterUniqueTogether(
            name='baseproperty',
            unique_together={('model', 'property')},
        ),
    ]
